/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Filme;
import javax.swing.JFrame;
import Model.Netflix;
import Model.Serie;
import javax.swing.JOptionPane;

/**
 *
 * @author EriikD
 */
public class ExcluirConteudo extends javax.swing.JFrame {

    private Netflix netflixBancoDeDados;
    private JFrame telaAdministrador;

    /**
     * Creates new form ExcluirConteudo
     */
    public ExcluirConteudo() {
        initComponents();
    }

    public ExcluirConteudo(Netflix netflixBancoDeDados, JFrame telaAdministrador) {
        this.netflixBancoDeDados = netflixBancoDeDados;
        this.telaAdministrador = telaAdministrador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeDoConteudo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        voltarTelaADMBotao = new javax.swing.JButton();
        checkFilme = new javax.swing.JCheckBox();
        checkSerie = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtDiretor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAtor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("EXCLUIR CONTEÚDO");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setText("NOME CONTEÚDO:");

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        voltarTelaADMBotao.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        voltarTelaADMBotao.setText("Voltar");
        voltarTelaADMBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTelaADMBotaoActionPerformed(evt);
            }
        });

        checkFilme.setText("Filme");
        checkFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFilmeActionPerformed(evt);
            }
        });

        checkSerie.setText("Serie");
        checkSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSerieActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("DIRETOR:");

        txtDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiretorActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("ATOR:");

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeDoConteudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAtor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiretor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                .addComponent(voltarTelaADMBotao)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(checkFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(nomeDoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(txtDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFilme)
                    .addComponent(checkSerie))
                .addGap(18, 18, 18)
                .addComponent(voltarTelaADMBotao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarTelaADMBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTelaADMBotaoActionPerformed
        this.setVisible(false);
        this.telaAdministrador.setVisible(true);
    }//GEN-LAST:event_voltarTelaADMBotaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nomeDoConteudoExcluir = this.nomeDoConteudo.getText();
        if (this.checkFilme.isSelected()) {
            Filme filmeRemover = this.netflixBancoDeDados.buscarFilme(nomeDoConteudoExcluir);
            if (filmeRemover != null) {
                this.netflixBancoDeDados.getFilmes().remove(filmeRemover);
                JOptionPane.showMessageDialog(null, "Filme removido com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Nao existe filme com o nome informado");
            }
        } else {
            Serie serieRemover = this.netflixBancoDeDados.buscarSerie(nomeDoConteudoExcluir);
            if (serieRemover != null) {
                this.netflixBancoDeDados.getSeries().remove(serieRemover);
                JOptionPane.showMessageDialog(null, "Serie removida com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Nao existe serie com o nome informado");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void checkFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFilmeActionPerformed
        if (this.checkFilme.isSelected()) {
            this.checkSerie.setEnabled(false);
        } else {
            this.checkSerie.setEnabled(true);
        }
    }//GEN-LAST:event_checkFilmeActionPerformed

    private void checkSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSerieActionPerformed
        if (this.checkSerie.isSelected()) {
            this.checkFilme.setEnabled(false);
        } else {
            this.checkFilme.setEnabled(true);
        }
    }//GEN-LAST:event_checkSerieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nomeDoConteudoExcluir = this.nomeDoConteudo.getText();
        if (this.checkFilme.isSelected()) {
            Filme filmeRemover = this.netflixBancoDeDados.buscarFilme(nomeDoConteudoExcluir);
            if (filmeRemover != null) {
                int indice = this.netflixBancoDeDados.getFilmes().indexOf(filmeRemover);
                netflixBancoDeDados.getFilmes().get(indice).setDiretor(null);
                JOptionPane.showMessageDialog(null, "Diretor removido com sucesso");
            }
        } else {
            Serie serieRemover = this.netflixBancoDeDados.buscarSerie(nomeDoConteudoExcluir);
            if (serieRemover != null) {
                int indice = this.netflixBancoDeDados.getSeries().indexOf(nomeDoConteudoExcluir);
                netflixBancoDeDados.getSeries().get(indice).setDiretor(null);
                JOptionPane.showMessageDialog(null, "Diretor removido com sucesso");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiretorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nomeDoConteudoExcluir = this.nomeDoConteudo.getText();
        String nomeDoAtorExcluir = this.txtAtor.getText();
        if (this.checkFilme.isSelected()) {
            Filme filmeRemover = this.netflixBancoDeDados.buscarFilme(nomeDoConteudoExcluir);
            if (filmeRemover != null) {
                for (int i = 0; i < filmeRemover.getListaDeAtores().length; i++) {
                    if (filmeRemover.getListaDeAtores()[i].equals(nomeDoAtorExcluir)) {
                        filmeRemover.getListaDeAtores()[i] = null;
                        filmeRemover.getListaDeAtores()[i] = "";
                    }

                }
                JOptionPane.showMessageDialog(null, "Ator removido com sucesso");
            }
        } else {
            Serie serieRemover = this.netflixBancoDeDados.buscarSerie(nomeDoConteudoExcluir);

            if (serieRemover != null) {
                for (int i = 0; i < serieRemover.getListaDeAtores().length; i++) {
                    if (serieRemover.getListaDeAtores()[i].equals(nomeDoAtorExcluir)) {
                        serieRemover.getListaDeAtores()[i] = null;
                        serieRemover.getListaDeAtores()[i] = "";
                    }
                }
                JOptionPane.showMessageDialog(null, "Ator removido com sucesso");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirConteudo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkFilme;
    private javax.swing.JCheckBox checkSerie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeDoConteudo;
    private javax.swing.JTextField txtAtor;
    private javax.swing.JTextField txtDiretor;
    private javax.swing.JButton voltarTelaADMBotao;
    // End of variables declaration//GEN-END:variables
}
